version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: Admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
