version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_db
    env_file:
      - .env
  bot:
    build: .
    command: python bot_main.py
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./input_data.sql:/docker-entrypoint-initdb.d/input_data.sql
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
