version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload --reload-dir /app
    volumes:
      - ./app:/app
      - ./images:/images
      - ./pdf_files:/pdf_files
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_db
    env_file:
      - .env
  bot:
    build: .
    command: python bot/bot_main.py
    restart: always
    volumes:
      - ./bot:/bot
      - ./app:/app
      - ./images:/images
      - ./pdf_files:/pdf_files
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_dbss
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  migrations:
    build: .
    command: alembic upgrade head
    volumes:
      - ./app:/app
      - ./alembic.ini:/alembic.ini
      - ./migrations:/migrations
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_db
    restart: no
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
