BOT_WELCOME_MESSAGE = '''Привет. Меня зовут Hike Helper.
Я помогу тебе разработать меню для твоего похода
и рассчитаю все необходимые для него продукты.
Выбери, что будем делать дальше:'''
BOT_WELCOME_MESSAGE_AND_CREATE_USER = '''Добро пожаловать в бот! Пропишите имя пользователя 
для использования нашего функционала:'''
CHOOSE_START_DATE = 'Выберите дату начала похода: '
START_CAMPAIGN_CREATE_1 = 'Отлично '
START_CAMPAIGN_CREATE_2 = ' теперь можно приступить к записи похода'
START_DATE = 'Дата начала похода '
END_DATE = 'Дата окончания похода '
ENTER_FIRST_MEAL = 'Введите первый прием пищи:'
CHOOSE_END_DATE = 'Выберите дату окончания похода: '
ENTER_LAST_MEAL = 'Введите последний прием пищи:'
FINAL_CAMP_CREATE_MSG_1 = '''Спасибо, данные у меня. 
Длительность похода составляет '''
FINAL_CAMP_CREATE_MSG_2 = '''. ID Вашей записи - '''
SHOW_MESSAGE_1 = 'Запись '
SHOW_MESSAGE_2 = '\nID записи - '
SHOW_MESSAGE_3 = '\nдата начала похода - '
SHOW_MESSAGE_4 = '\nдата окончания похода - '
SHOW_MESSAGE_5 = '\nпервый прием пищи - '
SHOW_MESSAGE_6 = '\nпоследний прием пищи - '
YOUR_DATA = 'Ваши данные\n:'
NO_DATA_MSG = 'У Вас пока нет записей, но можете их создать:'
PUT_RECORD_ID = 'Введите ID записи:'
WHAT_NEXT = 'Что будем делать дальше?'

BUTTON_DATE_SELECTION = 'выбрать дату окончания'
BUTTON_GO_TO_RECORD = 'Перейти к заполнению'
BUTTON_BREAKFAST = 'Завтрак'
BUTTON_LUNCH = 'Обед'
BUTTON_DINNER = 'Ужин'
BUTTON_GO_TO_MENU = 'Выйти в меню'
BUTTON_CREATE_MENU = 'Заполнить меню для похода'
BUTTON_SHOW_ALL = 'Показать все записи'
BUTTON_SHOW_SPECIFIC = 'Показать конкретную'
BUTTON_CHOOSE_OPTION = 'Выбирете опцию:'
BUTTON_CREATE = 'Создать запись'
BUTTON_SHOW = 'Показать запись'
BUTTON_CREATE_MENU = 'Составить меню для похода'

ERROR_NO_DATA = 'Такой в ваших записях нет. Попробуйте другой id'
ERROR_INVALID_DATA = '''Неправильная форма записи!
Введите пожалуйста, корректный id (натуральное число):'''