"""init

Revision ID: c03f88e3af77
Revises: 
Create Date: 2024-07-19 12:19:57.536201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



from app.insert_data import *

# revision identifiers, used by Alembic.
revision: str = 'c03f88e3af77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('tg_id', sa.Integer(), nullable=False),
        sa.Column('disabled', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('password'),
        sa.UniqueConstraint('tg_id'),
        sa.UniqueConstraint('username')
    )
    op.create_table(
        'campaigns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('startdate', sa.Date(), nullable=False),
        sa.Column('enddate', sa.Date(), nullable=False),
        sa.Column('firstfood', sa.Integer(), nullable=False),
        sa.Column('lastfood', sa.Integer(), nullable=False),
        sa.Column('user_tg_id', sa.Integer(), nullable=False),
        sa.CheckConstraint('firstfood IN (1, 2, 3)', name='check_firstfood'),
        sa.CheckConstraint('lastfood IN (1, 2, 3)', name='check_lastfood'),
        sa.ForeignKeyConstraint(['user_tg_id'], ['users.tg_id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'menu',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('feed_type', sa.String(length=255), nullable=False),
        sa.Column('feed_name', sa.String(length=255), nullable=False),
        sa.Column('product_name', sa.String(length=255), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('units', sa.String(length=255), nullable=False),
        sa.Column('food_preferences', sa.String(length=255), nullable=False),
        sa.Column('id_product', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'people',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('fio', sa.String(length=255), nullable=False),
        sa.Column('food_preferences', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # Вставка начальных данных
    bind = op.get_bind()
    for value, table in zip(values, tables):
        init_db(bind, value, table)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('menu')
    op.drop_table('campaigns')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
